routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return 'Olá seja bem-vimdo ao curso!';
});
*/

Route::get('/', 'MainController@main')->name('site.index')->middleware('log.acess');

Route::get('/about','AboutController@about')->name('site.about');

Route::get('/contact','ContactController@contact')->name('site.contact');

Route::post('/contact','ContactController@save')->name('site.contact');

Route::get('/login{error?}', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.login');


Route::middleware('authentication:default')->prefix('/app')->group(function(){

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    Route::get('/source', 'SourceController@index')->name('app.source');

    Route::post('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/add', 'SourceController@add')->name('app.source.add');

    Route::post('/source/add', 'SourceController@add')->name('app.source.add');

    Route::get('/source/edit/{id}/{msg?}', 'SourceController@edit')->name('app.source.edit');

    Route::get('/source/delete/{id}', 'SourceController@delete')->name('app.source.delete');

    //Products
    Route::resource('/product', 'ProductController');
    Route::delete('product.destroy/{product}', 'ProductController@destroy')->name('product.destroy');

      //ProductsDetails
      Route::resource('/product-detail', 'ProductDetailController');

      Route::resource('client', 'ClientController');
      Route::delete('client.destroy/{client}', 'ClientController@destroy')->name('client.destroy');

      Route::resource('order', 'OrderController');
      //Route::resource('order-product', 'OrderProductController');
      Route::get('order-product/create/{order}', 'OrderProductController@create')->name('order-product.create');
      Route::post('order-product/store/{order}', 'OrderProductController@store')->name('order-product.store');
     // Route::delete('order-product.destroy/{order}/{product}', 'OrderProductController@destroy')->name('order-product.destroy');
     Route::delete('order-product.destroy/{orderProduct}/{order_id}', 'OrderProductController@destroy')->name('order-product.destroy');
});

Route::get('/test/{p1}/{p2}', 'TestController@test')->name('test');

Route::fallback(function(){
    echo "This route doesn't exist, <a href='/'>click here</a> and go to homepage!";
});

//name, category, subject, message
/*
Route::get('/contact/{name}/{category_id}', function(
    string $name = 'Desconhecido',
    int $category_id = 1)//1 - 'Informação'
    {
        echo "Estamos aqui: $name - $category_id";
     })->where('categoty_id', '[0-9]+')->where('name', '[A-Za-z]+');
*/



/* http verbs: get, post, put, patch, delete, options*/

app/ProductDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductDetail extends Model
{
    protected $fillable = ['product_id','length', 'width', 'height', 'unity_id'];

    public function product(){
        return $this->belongsTo('App\Product');
    }
}

app/Http/Controllers/ProductDetailController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\ProductDetail;
use Illuminate\Http\Request;
use App\Product;
use App\Unity;
use App\ItemDetail;

class ProductDetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $product_detail = ProductDetail::all();
        return view('app.product_detail.index',['title'=>'Product_Detail', 'products_details' => $product_detail]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $unity = Unity::all();
        return view('app.product_detail.create_edit', ['title'=>'Create', 'unities'=> $unity]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rulls = [
            'product_id' => 'exists:products,id',
            'length' => 'required|integer',
            'width' => 'required|integer',
            'height' => 'required|integer',
            'unity_id' => 'exists:unities,id',
        ];

        $feedback =[
            'product_id.exists' => 'It must be a real product',
            'length.integer' => 'It must be an integer number',
            'width.integer' => 'It must be an integer number',
            'height.integer' => 'It must be an integer number',
            'unity_id.exists' => 'It must be a real unity'
        ];

        $request -> validate($rulls, $feedback);
        ProductDetail::create($request->all());

       return redirect()->route('product-detail.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  Integer $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product_detail = ItemDetail::find($id);
        return view('app.product_detail.show', ['title'=>'Show', 'product_detail'=> $product_detail]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Integer $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product_detail = ItemDetail::find($id);
        $unity = Unity::all();
        return view('app.product_detail.create_edit', ['title'=>'Edit', 'products_details'=> $product_detail, 'unities' => $unity]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ProductDetail  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductDetail $product_detail)
    {
        $product_detail->update($request->all());
       return redirect()->route('product-detail.show', ['title'=>'Update', 'product_detail' => $product_detail->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ProductDetail  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductDetail $product_detail)
    {
        $product_detail->delete();
        return redirect()->route('product-detail.index');
    }
}

resources/views/app/product_detail/create_edit.blade.php
        @extends('app.layouts.header')
        @if(isset($products_details->id))
             @section('title', $title)
            @else
            @section('title', $title)
            @endif

        @section('content')

        <div class="content">

            <div class="page-title-2">
            @if(isset($products_details->id))
            <h1>Products Details - Edit</h1>
            @else
            <h1>Products Details - Add</h1>
            @endif
            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('product-detail.index')}}">Back</a><li>
                        <li>Search<li>
                    </ul>
                </div>
                <div class="info-page">
                <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    @if(isset($products_details->id))
                <form method="POST" action="{{ route( 'product-detail.update', ['product_detail'=>$products_details->id] )}}">
                         @csrf
                         @method('PUT')


                <div>Name: {{ $products_details->item->name }}</div>
                <br>
                <div>Description: {{ $products_details->item->description }}</div>
                <br>
                        @else
                        <form method="POST" action="{{ route ('product-detail.store') }}">
                         @csrf
                         @endif
                        <input type="hidden" name="id" value="">
                           <label>Product ID</label>
                        <input type="text" name="product_id" value="{{ $products_details->product_id ?? old('product_id') }}" placeholder="Product ID" class="black-border">
                         {{ $errors->has('product_id') ? $errors->first('product_id') : '' }}
                            <label>Length</label>
                        <input type="text" name="length" value="{{ $products_details->length ?? old('length') }}" placeholder="Length" class="black-border">
                         {{ $errors->has('length') ? $errors->first('length') : '' }}
                            <label>Width</label>
                        <input type="text" name="width" value="{{ $products_details->width ?? old('width') }}" placeholder="Width" class="black-border">
                         {{ $errors->has('width') ? $errors->first('width') : '' }}
                            <label>Height</label>
                        <input type="text" name="height" value="{{ $products_details->height ?? old('height') }}" placeholder="Height" class="black-border">
                         {{ $errors->has('height') ? $errors->first('height') : '' }}
                        <select name="unity_id">
                            <option>»»Select Unity««</option>
                            @foreach ($unities as $unity)
                                  <option value="{{$unity->id}}" {{ ($products_details->unity_id ?? old('unity_id')) == $unity->id ? 'selected' : '' }}>{{$unity->description}}</option>
                            @endforeach
                        </select>
                         {{ $errors->has('unity_id') ? $errors->first('unity_id') : '' }}
                        <button type="submit" class="black-border">Submit</button>
                        </form>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/product_detail/index.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">
            <div class="page-title-2">
                <h1>Products Details - List</h1>
            </div>
                <div class="menu">
                    <ul>
                         <li><a href="{{route('product-detail.create')}}">New</a><li>
                       <li>Search<li>
                    </ul>
                </div>
                <div class="info-page">
                    <div style="width: 80%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    <table border="1" width="100%">
                    <thead>
                        <tr>
                            <th>Lenght</th>
                            <th>Width</th>
                            <th>Height</th>
                            <th>Product_id</th>
                            <th>Unity_id</th>
                            <th>Show</th>
                            <th colspan="2">#</th>
                        </tr>
                    </thead>
                    <tbody>
                      @foreach ($products_details as $product_detail)
                            <tr>
                                <td>{{ $product_detail->length }}</td>
                                <td>{{ $product_detail->width }}</td>
                                <td>{{ $product_detail->height }}</td>
                                <td>{{ $product_detail->product_id }}</td>
                                <td>{{ $product_detail->unity_id }}</td>
                                <td><a href="{{ route('product-detail.show', ['product_detail'=>$product_detail->id]) }}">Show</a></td>
                               <td><form id="form_{{$product_detail->id}}" method="POST" action="{{ route('product-detail.destroy', ['product_detail'=>$product_detail->id]) }}">
                                @method('DELETE')
                                @csrf
                                <!--<button type="submit">Delete</button>-->
                                <a href="#" onclick="document.getElementById('form_{{$product_detail->id}}').submit()">Delete</a></form></td>
                                <td><a href="{{ route('product-detail.edit', ['product_detail'=>$product_detail->id]) }}">Edit</a></td>
                            </tr>
                      @endforeach
                      </tbody>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/product_detail/show.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">

            <div class="page-title-2">
                <h1>Products - Details</h1>
            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('product-detail.index')}}">Back</a><li>
                        <li>Search<li>
                    </ul>
                </div>
                <div class="info-page">

            <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
             <h4>Product</h4>
                <div>Name: {{ $product_detail->item->name }}</div>
                <br>
                <div>Description: {{ $product_detail->item->description }}</div>
                <br>
                    <table border="1" width="100%">
                            <tr>
                                <td>ID Product</td>
                                <td>{{$product_detail->product_id}}</td>
                            </tr>
                              <tr>
                                <td>lenght</td>
                                <td>{{$product_detail->length}}</td>
                            </tr>
                            <tr>
                                <td>width</td>
                                <td>{{$product_detail->width}}</td>
                            </tr>
                            <tr>
                                <td>height</td>
                                <td>{{$product_detail->height}} Kg</td>
                            </tr>
                            <tr>
                                <td>Unity</td>
                                <td>{{$product_detail->unity_id}}</td>
                            </tr>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection