routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return 'Olá seja bem-vimdo ao curso!';
});
*/

Route::get('/', 'MainController@main')->name('site.index')->middleware('log.acess');

Route::get('/about','AboutController@about')->name('site.about');

Route::get('/contact','ContactController@contact')->name('site.contact');

Route::post('/contact','ContactController@save')->name('site.contact');

Route::get('/login{error?}', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.login');


Route::middleware('authentication:default')->prefix('/app')->group(function(){

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    Route::get('/source', 'SourceController@index')->name('app.source');

    Route::post('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/add', 'SourceController@add')->name('app.source.add');

    Route::post('/source/add', 'SourceController@add')->name('app.source.add');

    Route::get('/source/edit/{id}/{msg?}', 'SourceController@edit')->name('app.source.edit');

    Route::get('/source/delete/{id}', 'SourceController@delete')->name('app.source.delete');

    //Products
    Route::resource('/product', 'ProductController');
    Route::delete('product.destroy/{product}', 'ProductController@destroy')->name('product.destroy');

      //ProductsDetails
      Route::resource('/product-detail', 'ProductDetailController');

      Route::resource('client', 'ClientController');
      Route::delete('client.destroy/{client}', 'ClientController@destroy')->name('client.destroy');

      Route::resource('order', 'OrderController');
      //Route::resource('order-product', 'OrderProductController');
      Route::get('order-product/create/{order}', 'OrderProductController@create')->name('order-product.create');
      Route::post('order-product/store/{order}', 'OrderProductController@store')->name('order-product.store');
     // Route::delete('order-product.destroy/{order}/{product}', 'OrderProductController@destroy')->name('order-product.destroy');
     Route::delete('order-product.destroy/{orderProduct}/{order_id}', 'OrderProductController@destroy')->name('order-product.destroy');
});

Route::get('/test/{p1}/{p2}', 'TestController@test')->name('test');

Route::fallback(function(){
    echo "This route doesn't exist, <a href='/'>click here</a> and go to homepage!";
});

//name, category, subject, message
/*
Route::get('/contact/{name}/{category_id}', function(
    string $name = 'Desconhecido',
    int $category_id = 1)//1 - 'Informação'
    {
        echo "Estamos aqui: $name - $category_id";
     })->where('categoty_id', '[0-9]+')->where('name', '[A-Za-z]+');
*/



/* http verbs: get, post, put, patch, delete, options*/

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'description', 'weight', 'unity_id'];

    public function poductDetail(){
        return $this ->hasOne('App\ProductDetail');

       /* Product has one productDetail
        A register has joined with a product_detail (fk) -> product_id
        product (pk) -> id*/
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductDetail;
use App\Unity;
use Illuminate\Http\Request;
use App\Item;
use App\Source;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $products = Item::all();

       /* foreach($products as $key => $product){
            //print_r($product->getAttributes());
            //echo '<br><br>';

           $productDetail = ProductDetail::where('product_id', $product->id)->first();

            if(isset($productDetail)){
                //print_r($productDetail->getAttributes());

                $products[$key]['length'] = $productDetail->length;
                $products[$key]['width'] = $productDetail->width;
                $products[$key]['height'] = $productDetail->height;
            }

           // echo '<hr>';
        }*/

        return view('app.product.index',['title'=>'Product', 'products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $unities = Unity::all();
        $source = Source::all();
        return view('app.product.create_edit', ['title'=>'Create', 'unities'=> $unities, 'source'=> $source]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rulls = [
            'source_id' => 'exists:sources,id',
            'name' => 'required|min:3|max:40',
            'description' => 'required|min:5|max:2000',
            'weight' => 'required|integer',
            'unity_id' => 'exists:unities,id',
        ];

        $feedback =[
            'required' => 'Required field',
            'source_id.exists' => 'It must be a real name',
            'name.min' => 'You must put at least 3 character',
            'name.max' => 'The limit is 40 character',
            'description.min' => 'You must put at least 3 character',
            'description.max' => 'The limit is 2 character',
            'weight.integer' => 'It must be an integer number',
            'unity_id.exists' => 'It must be a real unity'
        ];

        $request -> validate($rulls, $feedback);
        Product::create($request->all());
       /*$product = new Product();
       $name = $request->get('name');
       $description = $request->get('description');

       $name = strtoupper($name);

       $product -> name = $name;
       $product -> description = $description;

       $product -> save();*/
       return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('app.product.show', ['title'=>'Show', 'products'=> $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $unity = Unity::all();
        $source = Source::all();
        //return view('app.product.edit', ['products'=> $product, 'unities' => $unity]);
        return view('app.product.create_edit', ['title'=>'Edit', 'products'=> $product, 'unities' => $unity, 'source'=> $source]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $product)
    {
       /*print_r($request->all());//playload
       echo '<br><br>';
       print_r($product->getAttributes());//object instant in last status*/
        //dd($request->all());
        $rulls = [
            'source_id' => 'exists:sources,id',
            'name' => 'required|min:3|max:40',
            'description' => 'required|min:5|max:2000',
            'weight' => 'required|integer',
            'unity_id' => 'exists:unities,id',
        ];

        $feedback =[
            'required' => 'Required field',
            'source_id.exists' => 'It must be a real name',
            'name.min' => 'You must put at least 3 character',
            'name.max' => 'The limit is 40 character',
            'description.min' => 'You must put at least 3 character',
            'description.max' => 'The limit is 2 character',
            'weight.integer' => 'It must be an integer number',
            'unity_id.exists' => 'It must be a real unity'
        ];

        $request -> validate($rulls, $feedback);
       $product->update($request->all());
       return redirect()->route('product.show', ['title'=>'Update', 'product' => $product->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('product.index');
    }
}

resources/views/app/product/create_edit.blade.php
        @extends('app.layouts.header')
        @if(isset($products->id))
             @section('title', $title)
            @else
            @section('title', $title)
            @endif

        @section('content')

        <div class="content">

            <div class="page-title-2">
            @if(isset($products->id))
            <h1>Products - Edit</h1>
            @else
            <h1>Products - Add</h1>
            @endif
            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('product.index')}}">Back</a><li>
                    </ul>
                </div>
                <div class="info-page">

                    <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                     @if(isset($products->id))
                <form method="POST" action="{{ route( 'product.update', ['product'=>$products->id] )}}">
                         @csrf
                         @method('PUT')
            @else
                        <form method="POST" action="{{ route ('product.store') }}">
                         @csrf
                         @endif
                              <select name="source_id">
                            <option>»»Select Source««</option>
                            @foreach ($source as $source)
                                  <option value="{{$source->id}}" {{ ($products->source_id ?? old('source_id')) == $source->id ? 'selected' : '' }}>{{$source->name}}</option>
                            @endforeach
                        </select>
                         {{ $errors->has('source_id') ? $errors->first('source_id') : '' }}
                        <input type="hidden" name="id" value="">
                           <label>Name</label>
                        <input type="text" name="name" value="{{ $products->name ?? old('name') }}" placeholder="name" class="black-border">
                         {{ $errors->has('name') ? $errors->first('name') : '' }}
                            <label>Description</label>
                        <input type="text" name="description" value="{{ $products->description ?? old('description') }}" placeholder="description" class="black-border">
                         {{ $errors->has('description') ? $errors->first('description') : '' }}
                            <label>Weight</label>
                        <input type="text" name="weight" value="{{ $products->weight ?? old('weight') }}" placeholder="weight" class="black-border">
                         {{ $errors->has('weight') ? $errors->first('weight') : '' }}
                        <select name="unity_id">
                            <option>»»Select Unity««</option>
                            @foreach ($unities as $unity)
                                  <option value="{{$unity->id}}" {{ ($products->unity_id ?? old('unity_id')) == $unity->id ? 'selected' : '' }}>{{$unity->description}}</option>
                            @endforeach
                        </select>
                         {{ $errors->has('unity_id') ? $errors->first('unity_id') : '' }}
                        <button type="submit" class="black-border">Submit</button>
                        </form>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/product/index.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">

            <div class="page-title-2">
                <h1>Products - List</h1>
            </div>
                <div class="menu">
                    <ul>
                         <li><a href="{{route('product.create')}}">New</a><li>
                       <li><a href="{{route('product-detail.index')}}">Product Details</a><li>
                    </ul>
                </div>
                <div class="info-page">
                    <div style="width: 80%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    <table border="1" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                             <th>Source</th>
                              <th>Source Site</th>
                            <th>Weight</th>
                            <th>Unity_id</th>
                            <th>Length</th>
                            <th>Width</th>
                             <th>Height</th>
                            <th colspan="3">#</th>
                        </tr>
                    </thead>
                    <tbody>

                      @foreach ($products as $product)
                            <tr>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->description }}</td>
                                <td>{{ $product->source->name }}</td>
                                <td>{{ $product->source->email }}</td>
                                <td>{{ $product->weight }}</td>
                                <td>{{ $product->unity_id }}</td>
                                 <td>{{ $product->itemDetail->length ?? '' }}</td>
                                  <td>{{ $product->itemDetail->width ?? '' }}</td>
                                   <td>{{ $product->itemDetail->height ?? '' }}</td>
                                <td><a href="{{ route('product.show', ['product'=>$product->id]) }}">Show</a></td>
                                <td><a href="{{ route('product.edit', ['product'=>$product->id]) }}">Edit</a></td>
                            </tr>

                            <tr>
                            <td colspan="12" align="center"><b>Orders</b><br>
                            @foreach ( $product->orders as $order)
                            <a href="{{route('order-product.create', ['order'=>$order->id])}}">
                            Order: {{$order->id}}, &nbsp;
                            </a>
                            @endforeach
                            </td>
                            </tr>
                      @endforeach
                      </tbody>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/product/show.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">

            <div class="page-title-2">
                <h1>Products - Details</h1>
            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('product.index')}}">Back</a><li>
                       
                    </ul>
                </div>
                <div class="info-page">

            <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    <table border="1" width="100%">
                            <tr>
                                <td>ID</td>
                                <td>{{$products->id}}</td>
                            </tr>
                              <tr>
                                <td>Name</td>
                                <td>{{$products->name}}</td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td>{{$products->description}}</td>
                            </tr>
                            <tr>
                                <td>Weight</td>
                                <td>{{$products->weight}} Kg</td>
                            </tr>
                            <tr>
                                <td>Unity</td>
                                <td>{{$products->unity_id}}</td>
                            </tr>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection