routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return 'Olá seja bem-vimdo ao curso!';
});
*/

Route::get('/', 'MainController@main')->name('site.index')->middleware('log.acess');

Route::get('/about','AboutController@about')->name('site.about');

Route::get('/contact','ContactController@contact')->name('site.contact');

Route::post('/contact','ContactController@save')->name('site.contact');

Route::get('/login{error?}', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.login');


Route::middleware('authentication:default')->prefix('/app')->group(function(){

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    Route::get('/source', 'SourceController@index')->name('app.source');

    Route::post('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/add', 'SourceController@add')->name('app.source.add');

    Route::post('/source/add', 'SourceController@add')->name('app.source.add');

    Route::get('/source/edit/{id}/{msg?}', 'SourceController@edit')->name('app.source.edit');

    Route::get('/source/delete/{id}', 'SourceController@delete')->name('app.source.delete');

    //Products
    Route::resource('/product', 'ProductController');
    Route::delete('product.destroy/{product}', 'ProductController@destroy')->name('product.destroy');

      //ProductsDetails
      Route::resource('/product-detail', 'ProductDetailController');

      Route::resource('client', 'ClientController');
      Route::delete('client.destroy/{client}', 'ClientController@destroy')->name('client.destroy');

      Route::resource('order', 'OrderController');
      //Route::resource('order-product', 'OrderProductController');
      Route::get('order-product/create/{order}', 'OrderProductController@create')->name('order-product.create');
      Route::post('order-product/store/{order}', 'OrderProductController@store')->name('order-product.store');
     // Route::delete('order-product.destroy/{order}/{product}', 'OrderProductController@destroy')->name('order-product.destroy');
     Route::delete('order-product.destroy/{orderProduct}/{order_id}', 'OrderProductController@destroy')->name('order-product.destroy');
});

Route::get('/test/{p1}/{p2}', 'TestController@test')->name('test');

Route::fallback(function(){
    echo "This route doesn't exist, <a href='/'>click here</a> and go to homepage!";
});

//name, category, subject, message
/*
Route::get('/contact/{name}/{category_id}', function(
    string $name = 'Desconhecido',
    int $category_id = 1)//1 - 'Informação'
    {
        echo "Estamos aqui: $name - $category_id";
     })->where('categoty_id', '[0-9]+')->where('name', '[A-Za-z]+');
*/



/* http verbs: get, post, put, patch, delete, options*/

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $client = Client::all();
        return view('app.client.index',['title'=>'Client', 'clients'=>$client]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('app.client.create_edit', ['title'=>'Create']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rulls = [
            'name' => 'required|min:3|max:40'
        ];

        $feedback = [
            'required' => 'This field is required',
            'name.min' => 'The name must have at least 3 character',
            'name.max' => 'The name must have 40 character'
        ];

        $request->validate($rulls, $feedback);
        $client = new Client();
        $client->name = $request->get('name');
        $client->save();

        return redirect()->route('client.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        return view('app.client.show', ['title'=>'Show', 'clients'=> $client]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        $clients = Client::all();
        return view('app.client.create_edit', ['title'=>'Edit', 'client'=> $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $rulls = [
            'name' => 'required|min:3|max:40'
        ];

        $feedback = [
            'required' => 'This field is required',
            'name.min' => 'The name must have at least 3 character',
            'name.max' => 'The name must have 40 character'
        ];

        $request->validate($rulls, $feedback);
        $client->update($request->all());
        return redirect()->route('client.show', ['title'=>'show', 'client' => $client->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return redirect()->route('client.index');
    }
}

resources/views/app/client/create_edit.blade.php
        @extends('app.layouts.header')
        @if(isset($client->id))
             @section('title', $title)
            @else
            @section('title', $title)
            @endif

        @section('content')

        <div class="content">

            <div class="page-title-2">
            @if(isset($client->id))
            <h1>Client - Edit</h1>
            @else
            <h1>Client - Add</h1>
            @endif
            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('client.index')}}">Back</a><li>
                    </ul>
                </div>
                <div class="info-page">

                    <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                     @if(isset($client->id))
                <form method="POST" action="{{ route( 'client.update', ['client'=>$client->id] )}}">
                         @csrf
                         @method('PUT')
                    @else
                        <form method="POST" action="{{ route ('client.store') }}">
                         @csrf
                           @endif
                        <input type="hidden" name="id" value="">
                        <input type="text" name="name" value="{{ $client->name ?? old('name') }}" placeholder="name" class="black-border">
                         {{ $errors->has('name') ? $errors->first('name') : '' }}
                        <button type="submit" class="black-border">Submit</button>
                        </form>
                    </div>
                </div>
        </div>

             <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/client/index.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">

            <div class="page-title-2">
                <h1>Client - List</h1>
            </div>
                <div class="menu">
                    <ul>
                         <li><a href="{{route('client.create')}}">New</a><li>
                    </ul>
                </div>
                <div class="info-page">
                    <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    <table border="1" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th colspan="3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                      @foreach ($clients as $client)
                            <tr>
                                <td>{{ $client->name }}</td>
                                <td><a href="{{ route('client.show', ['client'=>$client->id]) }}">Show</a></td>
                                <td><a href="{{ route('client.edit', ['client'=>$client->id]) }}">Edit</a></td>
                            </tr>
                      @endforeach
                      </tbody>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/client/show.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">

            <div class="page-title-2">
                <h1>Client - Details</h1>
            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('client.index')}}">Back</a><li>

                    </ul>
                </div>
                <div class="info-page">

            <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    <table border="1" width="100%">
                              <tr>
                                <td><b>Name</b></td>
                                <td>{{$clients->name}}</td>
                            </tr>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection