routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return 'Olá seja bem-vimdo ao curso!';
});
*/

Route::get('/', 'MainController@main')->name('site.index')->middleware('log.acess');

Route::get('/about','AboutController@about')->name('site.about');

Route::get('/contact','ContactController@contact')->name('site.contact');

Route::post('/contact','ContactController@save')->name('site.contact');

Route::get('/login{error?}', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.login');


Route::middleware('authentication:default')->prefix('/app')->group(function(){

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    Route::get('/source', 'SourceController@index')->name('app.source');

    Route::post('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/list', 'SourceController@list')->name('app.source.list');

    Route::get('/source/add', 'SourceController@add')->name('app.source.add');

    Route::post('/source/add', 'SourceController@add')->name('app.source.add');

    Route::get('/source/edit/{id}/{msg?}', 'SourceController@edit')->name('app.source.edit');

    Route::get('/source/delete/{id}', 'SourceController@delete')->name('app.source.delete');

    //Products
    Route::resource('/product', 'ProductController');
    Route::delete('product.destroy/{product}', 'ProductController@destroy')->name('product.destroy');

      //ProductsDetails
      Route::resource('/product-detail', 'ProductDetailController');

      Route::resource('client', 'ClientController');
      Route::delete('client.destroy/{client}', 'ClientController@destroy')->name('client.destroy');

      Route::resource('order', 'OrderController');
      //Route::resource('order-product', 'OrderProductController');
      Route::get('order-product/create/{order}', 'OrderProductController@create')->name('order-product.create');
      Route::post('order-product/store/{order}', 'OrderProductController@store')->name('order-product.store');
     // Route::delete('order-product.destroy/{order}/{product}', 'OrderProductController@destroy')->name('order-product.destroy');
     Route::delete('order-product.destroy/{orderProduct}/{order_id}', 'OrderProductController@destroy')->name('order-product.destroy');
});

Route::get('/test/{p1}/{p2}', 'TestController@test')->name('test');

Route::fallback(function(){
    echo "This route doesn't exist, <a href='/'>click here</a> and go to homepage!";
});

//name, category, subject, message
/*
Route::get('/contact/{name}/{category_id}', function(
    string $name = 'Desconhecido',
    int $category_id = 1)//1 - 'Informação'
    {
        echo "Estamos aqui: $name - $category_id";
     })->where('categoty_id', '[0-9]+')->where('name', '[A-Za-z]+');
*/



/* http verbs: get, post, put, patch, delete, options*/

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function products(){
        return $this->belongsToMany('App\Product', 'orders_products')->withPivot('created_at', 'id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $order = Order::all();
        return view('app.order.index', ['title'=>'Order', 'orders'=>$order]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $client = Client::all();
        return view('app.order.create_edit', ['title'=>'Create', 'clients'=>$client]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rulls = [
            'client_id' => 'exists:clients,id'
        ];

        $feedback =[
            'required' => 'Required field',
            'client_id.exists' => 'It must be a real name',
        ];

        $request -> validate($rulls, $feedback);
        $order = new Order();
        $order->client_id = $request->get('client_id');
        $order->save();

        return redirect()->route('order.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( $id)
    {
       //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app/order/create_edit.blade.php
        @extends('app.layouts.header')

            @section('title', $title)


        @section('content')

        <div class="content">

            <div class="page-title-2">

            <h1>Order - Add</h1>

            </div>
                <div class="menu">
                    <ul>
                        <li><a href="{{route('order.index')}}">Back</a><li>
                    </ul>
                </div>
                <div class="info-page">

                    <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">

                        <form method="POST" action="{{ route ('order.store') }}">
                         @csrf
                              <select name="client_id">
                            <option>»»Select Client««</option>
                            @foreach ($clients as $client)
                                  <option value="{{$client->id}}" {{ ($order->client_id ?? old('client_id')) == $client->id ? 'selected' : '' }}>{{$client->name}}</option>
                            @endforeach
                        </select>
                         {{ $errors->has('client_id') ? $errors->first('client_id') : '' }}
                        <input type="hidden" name="id" value="">

                        <button type="submit" class="black-border">Submit</button>
                        </form>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection

resources/views/app/order/index.blade.php
        @extends('app.layouts.header')
        @section('title', $title)
        @section('content')

        <div class="content">

            <div class="page-title-2">
                <h1>Order - List</h1>
            </div>
                <div class="menu">
                    <ul>
                         <li><a href="{{route('order.create')}}">New</a><li>
                    </ul>
                </div>
                <div class="info-page">
                    <div style="width: 30%; margin-left: auto; margin-right: auto; margin-top: 5rem;">
                    <table border="1" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Client</th>
                            <th colspan="3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                      @foreach ($orders as $order)
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->client_id }}</td>
                                <td><a href="{{ route('order-product.create', ['order'=>$order->id]) }}">Add product</a></td>
                            </tr>
                      @endforeach
                      </tbody>
                      </table>
                    </div>
                </div>
        </div>


            <div class="footer">
                    <div class="network">
                        <h2>Social Network</h2>
                        <img src="/img/facebook.png">
                        <img src="/img/linkedin.png">
                        <img src="/img/youtube.png">
                    </div>
                    <div class="area-contact">
                        <h2>Contact</h2>
                        <span>(11) 3333-4444</span>
                        <br>
                        <span>supergestao@dominio.com.br</span>
                    </div>
                    <div class="localization">
                        <h2>Localization</h2>
                        <img src="/img/mapa.png">
                    </div>
                </div>
        @endsection